# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9be633f42d52f5d2f6dac61366895876084e3c770c81a65ae9d1db0d030202b11b7f792d0cee72c2f0588b301d68b3a5290d64dd78685e56a405a5087a5f2b00

test:
  secret_key_base: 460faa9e6b15d03f694d5c21ac8b95b56ff1df5cf4301701c6cd2a3bbb6948c75a3868b59368bdfe40a57a3b086b83a6d8054073351ab0a1b00b9f5606af9132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
